name: Publish Package to npmjs
on:
   push: 
        branches:
             - main
   pull_request:
        branches:
            - main
   release:
        types: [created]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.HUB_TOKEN }}
          version-file: './package.json,./package-lock.json'
      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
  publish-gpr:
    needs: changelog
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
      - run: npm ci
      - run: npm run build
      - run: |
          echo @SUNNYKUMAR1232:registry=https://registry.npmjs.org/>build/.npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>>build/.npmrc
      - run: npm publish --provenance --access public
        working-directory: ./build
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}



