name: Publish Package to npmjs
on:
   push: 
        branches:
             - main
   pull_request:
        branches:
            - main
   release:
        types: [created]
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
      - run: npm ci
      - run: npm run build
      - run: |
          echo @SUNNYKUMAR1232:registry=https://registry.npmjs.org/>build/.npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>>build/.npmrc
      - run: npm publish --provenance --access public
        working-directory: ./build
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}



